from PyQt5 import QtGui
from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5.QtWidgets import *
from DbAccess.controller import *



class AddStudentInfoPage(QWidget):
    def __init__(self, parent= None):
        super(AddStudentInfoPage, self).__init__(parent)
        self.showrno = QtWidgets.QLineEdit(self)
        self.showrno.move(145,125)
        self.showrno.setStyleSheet("background-color: rgb(255,255,255);")
        self.setupUi()

    def setupUi(self):
        self.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                           "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                           "border-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(60, 100, 641, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 721, 301))
        self.frame_2.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                                   "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                                   "border-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.heading = QtWidgets.QLabel("Add Student Details",self)
        self.heading.move(80,90)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.heading.setFont(font)
        self.rollno = QtWidgets.QLabel("Roll No:", self)
        self.rollno.move(80,145)
        self.enterrollno = QtWidgets.QLineEdit(self)
        self.enterrollno.move(145,145)
        self.enterrollno.setEnabled(False)
        self.enterrollno.setStyleSheet("background-color: rgb(255,255,255);")
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollno.setFont(font)
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 50, 271, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.name.setFont(font)
        self.name.setObjectName("label")
        self.horizontalLayout.addWidget(self.name)
        self.entername = QtWidgets.QLineEdit(self.widget)
        self.entername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entername.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.entername)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(380, 50, 241, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.phnno = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.phnno.setFont(font)
        self.phnno.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.phnno)
        self.enterphnno = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.enterphnno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterphnno.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.enterphnno)
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.address = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.address.setFont(font)
        self.address.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.address)
        self.enteraddress = QtWidgets.QLineEdit(self.layoutWidget)
        self.enteraddress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enteraddress.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.enteraddress)

        self.widget1 = QtWidgets.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(380, 100, 241, 21))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gender = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.gender.setFont(font)
        self.gender.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.gender)
        self.maleButton = QtWidgets.QRadioButton(self.widget1)
        self.maleButton.setObjectName("radioButton")
        self.horizontalLayout_4.addWidget(self.maleButton)
        self.femaleButton = QtWidgets.QRadioButton(self.widget1)
        self.femaleButton.setObjectName("radioButton_2")
        self.horizontalLayout_4.addWidget(self.femaleButton)
        self.widget2 = QtWidgets.QWidget(self.frame_2)
        self.widget2.setGeometry(QtCore.QRect(10, 150, 271, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DOA = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.DOA.setFont(font)
        self.DOA.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.DOA)
        self.enterdate = QtWidgets.QDateEdit(self.widget2)
        self.enterdate.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.enterdate.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.enterdate.setCalendarPopup(True)
        self.enterdate.setObjectName("dateEdit")
        self.horizontalLayout_5.addWidget(self.enterdate)
        self.widget3 = QtWidgets.QWidget(self.frame_2)
        self.widget3.setGeometry(QtCore.QRect(380, 150, 241, 22))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.course = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.course.setFont(font)
        self.course.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.course)
        self.selectcourse = QtWidgets.QComboBox(self.widget3)
        self.selectcourse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectcourse.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.selectcourse)
        self.submitButton = QtWidgets.QPushButton(self.frame_2)
        self.submitButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                        "background-color: qconicalgradient(cx:0, cy:0,"
                                        " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                        " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                        " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                        " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                        "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                        " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.submitButton.setGeometry(QtCore.QRect(260, 220, 131, 31))
        self.submitButton.setObjectName("pushButton")
        self.retranslateUi()
        #QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.address.setText(_translate("Form", "Address:"))
        self.phnno.setText(_translate("Form", "Phone No:"))
        self.submitButton.setText(_translate("Form", "Submit"))
        self.name.setText(_translate("Form", "Name:"))
        self.gender.setText(_translate("Form", "Gender:"))
        self.maleButton.setText(_translate("Form", "Male"))
        self.femaleButton.setText(_translate("Form", "Female"))
        self.DOA.setText(_translate("Form", "Date of Admission:"))
        self.course.setText(_translate("Form", "Course:"))
        self.enterphnno.setText("")
        self.entername.setText("")
        self.enteraddress.setText("")
        self.enterdate.setDate(QtCore.QDate.currentDate())
        self.selectcourse.setCurrentIndex(0)
        self.maleButton.setChecked(True)

    def updateCoursesInList(self):
        updates = StudentDataIntoDb()
        list = updates.getcoursesforlist()
        self.selectcourse.clear()
        for coursename in list:
            self.selectcourse.addItem(coursename[0])

class insertStudentDsts():
    def insert(self,addstudet):
        name = addstudet.entername.text()
        phn = addstudet.enterphnno.text()
        address = addstudet.enteraddress.text()
        DOA = addstudet.enterdate.text()
        date = DOA.split('-',2)
        d = QtCore.QDate(int(date[2]), int(date[1]), int(date[0]))
        DOI = d.addMonths(1).toString(QtCore.Qt.DefaultLocaleShortDate)
        course = addstudet.selectcourse.currentText()
        if '' in (name,phn,address,DOA,course,DOI):
            return False
        else:
            phn_nos = phn.split(",",phn.count(','))
            for i in range(phn.count(',') + 1):
                try:
                    if int(phn_nos[i]) > 999999999 and int(phn_nos[i]) < 10000000000:
                        pass
                    else:
                        return False
                except ValueError:
                    return False
            insertintodb = StudentDataIntoDb()
            if addstudet.maleButton.isChecked():
                gender = 'M'
                if insertintodb.insertIntoDb(name, phn, address, gender, DOA, course, DOI):
                    return True
                else:
                    return False
            elif addstudet.femaleButton.isChecked():
                gender = 'F'
                if insertintodb.insertIntoDb(name, phn, address, gender, DOA, course, DOI):
                    return True
                else:
                    return False
            else:
                return False

    def show_rno(self,addstudet):
        insert = StudentDataIntoDb()
        rno = insert.showrollno()
        addstudet.enterrollno.setText(str(rno))

class SearchforUpdatePage(QWidget):
    def __init__(self, parent= None):
        super(SearchforUpdatePage, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                           "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                           "border-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(60, 100, 641, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 721, 301))
        self.frame_2.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                                   "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                                   "border-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.heading = QtWidgets.QLabel("Update Student Details",self)
        self.heading.move(80,90)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.heading.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.searchButton = QtWidgets.QPushButton(self.frame_2)
        self.searchButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                            "background-color: qconicalgradient(cx:0, cy:0,"
                                            " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                            " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                            " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                            " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                            "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                            " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.searchButton.setGeometry(QtCore.QRect(60, 100, 131, 31))
        self.searchButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 50, 271, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rollno = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollno.setFont(font)
        self.rollno.setObjectName("label")
        self.horizontalLayout.addWidget(self.rollno)
        self.enterrollno = QtWidgets.QLineEdit(self.widget)
        self.enterrollno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterrollno.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.enterrollno)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.rollno.setText(_translate("Form", "Roll No:"))
        self.searchButton.setText(_translate("Form", "Search"))

    def searchrollno(self,updatepage):
        rollno = self.enterrollno.text()
        try:
            if int(rollno)>0:
                self.viewdata = ViewStudentData(rollno,'Single')
                data = self.viewdata.returndata()
                updatepage.viewdatatoupdate(data)
                return True
        except ValueError:
            return False

class updateStudentPage(QWidget):
    def __init__(self, parent= None):
        super(updateStudentPage, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                           "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                           "border-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(60, 100, 641, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 721, 301))
        self.frame_2.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                                   "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                                   "border-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.heading = QtWidgets.QLabel("Update Student Details",self)
        self.heading.move(80,90)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.heading.setFont(font)
        self.rollno = QtWidgets.QLabel("Roll No:",self)
        self.rollno.move(80,145)
        self.enterrollno = QtWidgets.QLineEdit(self)
        self.enterrollno.move(145,145)
        self.enterrollno.setStyleSheet("background-color: rgb(255,255,255);")
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollno.setFont(font)
        self.enterrollno.setEnabled(False)
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 50, 271, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.name.setFont(font)
        self.name.setObjectName("label")
        self.horizontalLayout.addWidget(self.name)
        self.entername = QtWidgets.QLineEdit(self.widget)
        self.entername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entername.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.entername)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(380, 50, 241, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.phnno = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.phnno.setFont(font)
        self.phnno.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.phnno)
        self.enterphnno = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.enterphnno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterphnno.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.enterphnno)
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.address = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.address.setFont(font)
        self.address.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.address)
        self.enteraddress = QtWidgets.QLineEdit(self.layoutWidget)
        self.enteraddress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enteraddress.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.enteraddress)

        self.widget1 = QtWidgets.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(380, 100, 241, 21))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gender = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.gender.setFont(font)
        self.gender.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.gender)
        self.maleButton = QtWidgets.QRadioButton(self.widget1)
        self.maleButton.setObjectName("radioButton")
        self.horizontalLayout_4.addWidget(self.maleButton)
        self.femaleButton = QtWidgets.QRadioButton(self.widget1)
        self.femaleButton.setObjectName("radioButton_2")
        self.horizontalLayout_4.addWidget(self.femaleButton)
        self.widget2 = QtWidgets.QWidget(self.frame_2)
        self.widget2.setGeometry(QtCore.QRect(10, 150, 271, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DOA = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.DOA.setFont(font)
        self.DOA.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.DOA)
        self.enterdate = QtWidgets.QDateEdit(self.widget2)
        self.enterdate.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        #self.enterdate.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.enterdate.setCalendarPopup(True)
        self.enterdate.setObjectName("dateEdit")
        self.horizontalLayout_5.addWidget(self.enterdate)

        self.widget3 = QtWidgets.QWidget(self.frame_2)
        self.widget3.setGeometry(QtCore.QRect(380, 150, 241, 22))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.course = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.course.setFont(font)
        self.course.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.course)
        self.selectcourse = QtWidgets.QComboBox(self.widget3)
        self.selectcourse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectcourse.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.selectcourse)
        self.widget4 = QtWidgets.QWidget(self.frame_2)
        self.widget4.setGeometry(QtCore.QRect(10, 200, 271, 22))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.status = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.status.setFont(font)
        self.status.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.status)
        self.showstatus = QtWidgets.QComboBox(self.widget4)
        self.showstatus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.showstatus.setObjectName("comboBox_2")
        self.showstatus.addItem("")
        self.showstatus.addItem("")
        self.horizontalLayout_8.addWidget(self.showstatus)
        self.certificate = QtWidgets.QCheckBox(self.widget4)
        self.certificate.setObjectName("checkBox")
        self.horizontalLayout_8.addWidget(self.certificate)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(380, 200, 241, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.feeremaining = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.feeremaining.setFont(font)
        self.feeremaining.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.feeremaining)
        self.enterfee = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.enterfee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterfee.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.enterfee)
        self.submitButton = QtWidgets.QPushButton(self.frame_2)
        self.submitButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                        "background-color: qconicalgradient(cx:0, cy:0,"
                                        " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                        " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                        " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                        " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                        "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                        " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.submitButton.setGeometry(QtCore.QRect(200, 250, 131, 31))
        self.submitButton.setObjectName("pushButton")
        self.cancelButton = QtWidgets.QPushButton(self.frame_2)
        self.cancelButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                        "background-color: qconicalgradient(cx:0, cy:0,"
                                        " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                        " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                        " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                        " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                        "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                        " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.cancelButton.setGeometry(QtCore.QRect(350, 250, 131, 31))
        self.cancelButton.setObjectName("pushButton_2")
        self.retranslateUi()


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.address.setText(_translate("Form", "Address:"))
        self.phnno.setText(_translate("Form", "Phone No:"))
        self.submitButton.setText(_translate("Form", "Update"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.name.setText(_translate("Form", "Name:"))
        self.gender.setText(_translate("Form", "Gender:"))
        self.maleButton.setText(_translate("Form", "Male"))
        self.femaleButton.setText(_translate("Form", "Female"))
        self.DOA.setText(_translate("Form", "Date of Admission:"))
        self.course.setText(_translate("Form", "Course:"))
        self.status.setText(_translate("Form", "Status:"))
        self.showstatus.setItemText(0, _translate("Form", "Studying"))
        self.showstatus.setItemText(1, _translate("Form", "Completed"))
        self.certificate.setText(_translate("Form", "Certificate:"))
        self.feeremaining.setText(_translate("Form", "Fess Remaining:"))
        self.enterphnno.setText("")
        self.entername.setText("")
        self.enteraddress.setText("")
        self.enterdate.setDate(QtCore.QDate.currentDate())
        self.selectcourse.setCurrentIndex(0)
        self.maleButton.setChecked(True)
        self.enterfee.setText("0")
        self.certificate.setChecked(False)


    def updateCoursesInList(self):
        updates = StudentDataIntoDb()
        list = updates.getcoursesforlist()
        self.selectcourse.clear()
        for coursename in list:
            self.selectcourse.addItem(coursename[0])

    def viewdatatoupdate(self,data):
        self.updateCoursesInList()
        for eachdata in data:
            self.enterrollno.setText(str(eachdata[0]))
            self.entername.setText(eachdata[1])
            self.enterphnno.setText(eachdata[2])
            self.enteraddress.setText(eachdata[3])
            if eachdata[4] == 'F':
                self.femaleButton.setChecked(True)
            else:
                self.maleButton.setChecked(True)
            print("dateinupdate" + str(eachdata[5]))
            dates = str(eachdata[5]).split('-',2)
            print(dates)
            self.enterdate.setDateTime(QtCore.QDateTime(QtCore.QDate(int(dates[2]),int(dates[1]),int(dates[0])), QtCore.QTime(0, 0, 0)))
            for i in range(0,self.selectcourse.count()):
                if self.selectcourse.itemText(i) == eachdata[6]:
                    self.selectcourse.setCurrentIndex(i)
            self.enterfee.setText(str(eachdata[7]))
            if eachdata[8] == 'Y':
                self.certificate.setChecked(True)
            for i in range(0,self.showstatus.count()):
                if self.selectcourse.itemText(i) == eachdata[9]:
                    self.selectcourse.setCurrentIndex(i)

    def updateStudentDataIntoDb(self):
        print("in")
        rollno = self.enterrollno.text()
        name = self.entername.text()
        phn = self.enterphnno.text()
        address = self.enteraddress.text()
        DOA = self.enterdate.text()
        course = self.selectcourse.currentText()
        if self.certificate.isChecked():
            certificate = 'Y'
        else:
            certificate = 'N'
        status = self.showstatus.currentText()
        updateintodb = StudentDataIntoDb()
        if self.maleButton.isChecked():
            gender = 'M'
            if updateintodb.updateIntoDb(rollno,name, phn, address, gender, DOA, course, certificate, status):
                return True
            else:
                return False
        elif self.femaleButton.isChecked():
            gender = 'F'
            if updateintodb.updateIntoDb(rollno,name, phn, address, gender, DOA, course, certificate, status):
                return True
            else:
                return False
        else:
            return False




class SearchStudentPage(QWidget):
    def __init__(self, parent= None):
        super(SearchStudentPage, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                           "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                           "border-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(60, 100, 641, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 721, 301))
        self.frame_2.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                                   "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                                   "border-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.heading = QtWidgets.QLabel("Search Student",self)
        self.heading.move(80,90)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.heading.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.searchButton = QtWidgets.QPushButton(self.frame_2)
        self.searchButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                            "background-color: qconicalgradient(cx:0, cy:0,"
                                            " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                            " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                            " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                            " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                            "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                            " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.searchButton.setGeometry(QtCore.QRect(60, 100, 131, 31))
        self.searchButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(270, 55, 271, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rollno = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollno.setFont(font)
        self.rollno.setObjectName("label")
        self.horizontalLayout.addWidget(self.rollno)
        self.enterrollno = QtWidgets.QLineEdit(self.widget)
        self.enterrollno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterrollno.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.enterrollno)
        self.widget.hide()
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setGeometry(QtCore.QRect(10, 55, 200, 22))
        self.widget_2.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.noofrec = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.noofrec.setFont(font)
        self.noofrec.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.noofrec)
        self.enternoofrec = QtWidgets.QComboBox(self.widget_2)
        self.enternoofrec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enternoofrec.setObjectName("combobox")
        self.horizontalLayout_2.addWidget(self.enternoofrec)
        self.enternoofrec.addItem("All")
        self.enternoofrec.addItem("Single")
        self.retranslateUi()

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.rollno.setText(_translate("Form", "Roll No:"))
        self.searchButton.setText(_translate("Form", "Search"))
        self.noofrec.setText(_translate("Form", "Show"))
        self.enterrollno.setText('')

    def searchrollno(self,searchedpage):
        rollno = self.enterrollno.text()
        try:
            num = self.enternoofrec.currentText()
            if num == 'Single':
                if int(rollno)>0:
                    self.viewdata = ViewStudentData(rollno,num)
                else:
                    return False
            else:
                self.viewdata = ViewStudentData(rollno, num)
            data = self.viewdata.returndata()
            if self.enternoofrec.currentText() == 'Single':
                searchedpage.viewdatatosearch(data)
            else:
                searchedpage.viewintable(data)
            return True
        except ValueError:
            return False

    def showrollno(self):
        if self.enternoofrec.currentText() == 'Single':
            self.widget.show()
        else:
            self.widget.hide()
            self.enterrollno.setText("")

class StudentSearchedPage(QWidget):
    def __init__(self, parent= None):
        super(StudentSearchedPage, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                           "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                           "border-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(60, 100, 641, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 721, 301))
        self.frame_2.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                                   "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                                   "border-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.heading = QtWidgets.QLabel("Search Student",self)
        self.heading.move(80,90)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.heading.setFont(font)
        self.rollno = QtWidgets.QLabel("Roll No:",self)
        self.rollno.move(80,145)
        self.enterrollno = QtWidgets.QLineEdit(self)
        self.enterrollno.move(145,145)
        self.enterrollno.setEnabled(False)
        self.enterrollno.setStyleSheet("background-color: rgb(255,255,255);")
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollno.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.address = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.address.setFont(font)
        self.address.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.address)
        self.enteraddress = QtWidgets.QLineEdit(self.layoutWidget)
        self.enteraddress.setEnabled(False)
        self.enteraddress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enteraddress.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.enteraddress)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(380, 50, 241, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.phnno = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.phnno.setFont(font)
        self.phnno.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.phnno)
        self.enterphnno = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.enterphnno.setEnabled(False)
        self.enterphnno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterphnno.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.enterphnno)
        self.backButton = QtWidgets.QPushButton(self)
        self.backButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                            "background-color: qconicalgradient(cx:0, cy:0,"
                                            " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                            " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                            " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                            " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                            "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                            " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.backButton.setGeometry(QtCore.QRect(310, 450, 131, 31))
        self.backButton.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 50, 271, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.name.setFont(font)
        self.name.setObjectName("label")
        self.horizontalLayout.addWidget(self.name)
        self.entername = QtWidgets.QLineEdit(self.widget)
        self.entername.setEnabled(False)
        self.entername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entername.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.entername)
        self.widget1 = QtWidgets.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(380, 100, 241, 21))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gender = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.gender.setFont(font)
        self.gender.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.gender)
        self.maleButton = QtWidgets.QRadioButton(self.widget1)
        self.maleButton.setObjectName("radioButton")
        self.maleButton.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.maleButton)
        self.femaleButton = QtWidgets.QRadioButton(self.widget1)
        self.femaleButton.setObjectName("radioButton_2")
        self.femaleButton.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.femaleButton)
        self.widget2 = QtWidgets.QWidget(self.frame_2)
        self.widget2.setGeometry(QtCore.QRect(10, 150, 271, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DOA = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.DOA.setFont(font)
        self.DOA.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.DOA)
        self.enterdate = QtWidgets.QLineEdit(self.widget2)
        self.enterdate.setEnabled(False)
        self.enterdate.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.enterdate.setObjectName("dateEdit")
        self.horizontalLayout_5.addWidget(self.enterdate)
        self.widget3 = QtWidgets.QWidget(self.frame_2)
        self.widget3.setGeometry(QtCore.QRect(380, 150, 241, 22))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.course = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.course.setFont(font)
        self.course.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.course)
        self.selectcourse = QtWidgets.QLineEdit(self.widget3)
        self.selectcourse.setEnabled(False)
        self.selectcourse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout_6.addWidget(self.selectcourse)

        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(380, 200, 241, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.feeremaining = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.feeremaining.setFont(font)
        self.feeremaining.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.feeremaining)
        self.enterfee = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.enterfee.setEnabled(False)
        self.enterfee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterfee.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.enterfee)
        self.widget4 = QtWidgets.QWidget(self.frame_2)
        self.widget4.setGeometry(QtCore.QRect(10, 200, 271, 22))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.status = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.status.setFont(font)
        self.status.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.status)
        self.showstatus = QtWidgets.QLineEdit(self.widget4)
        self.showstatus.setEnabled(False)
        self.showstatus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.showstatus.setObjectName("comboBox_2")
        self.horizontalLayout_8.addWidget(self.showstatus)
        self.certificate = QtWidgets.QCheckBox(self.widget4)
        self.certificate.setObjectName("checkBox")
        self.certificate.setEnabled(False)
        self.horizontalLayout_8.addWidget(self.certificate)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.table = QtWidgets.QTableWidget(self)
        self.table.setColumnCount(10)
        self.table.setHorizontalHeaderLabels(('Roll No','Name','Phone No','Address',
                                              'Gender','Date Of Admission','Course','Fees','Certificate','Status'))
        self.table.setGeometry(30,120,700,300)
        self.table.verticalHeader().hide()
        self.table.setColumnWidth(0,80)
        self.table.setColumnWidth(1,130)
        self.table.setColumnWidth(3,160)
        self.table.setColumnWidth(4,50)
        self.table.setColumnWidth(6,80)
        self.table.setColumnWidth(7,80)
        self.table.setColumnWidth(8,80)
        self.table.setColumnWidth(9,80)
        self.table.setStyleSheet("background-color: rgb(255,255,255);")
        self.retranslateUi()


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.address.setText(_translate("Form", "Address:"))
        self.phnno.setText(_translate("Form", "Phone No:"))
        self.backButton.setText(_translate("Form", "Back"))
        self.name.setText(_translate("Form", "Name:"))
        self.gender.setText(_translate("Form", "Gender:"))
        self.maleButton.setText(_translate("Form", "Male"))
        self.femaleButton.setText(_translate("Form", "Female"))
        self.DOA.setText(_translate("Form", "Date of Admission:"))
        self.course.setText(_translate("Form", "Course:"))
        self.status.setText(_translate("Form", "Status:"))
        self.certificate.setText(_translate("Form", "Certificate:"))
        self.feeremaining.setText(_translate("Form", "Fess Remaining:"))
        self.enterphnno.setText("")
        self.entername.setText("")
        self.enteraddress.setText("")
        self.enterdate.setText("")
        self.selectcourse.setText("")
        self.maleButton.setChecked(True)
        self.enterfee.setText("0")
        self.certificate.setChecked(False)


    def viewdatatosearch(self,data):
        self.hiddingWidgets()
        self.rollno.show()
        self.enterrollno.show()
        self.widget.show()
        self.widget1.show()
        self.widget2.show()
        self.widget3.show()
        self.widget4.show()
        self.layoutWidget.show()
        self.layoutWidget_2.show()
        self.layoutWidget_3.show()
        for eachdata in data:
            self.enterrollno.setText(str(eachdata[0]))
            self.entername.setText(eachdata[1])
            self.enterphnno.setText(eachdata[2])
            self.enteraddress.setText(eachdata[3])
            if eachdata[4] == 'F':
                self.femaleButton.setChecked(True)
            else:
                self.maleButton.setChecked(True)
            self.enterdate.setText(str(eachdata[5]))
            self.selectcourse.setText(eachdata[6])
            self.enterfee.setText(str(eachdata[7]))
            if eachdata[8] == 'Y':
                self.certificate.setChecked(True)
            self.showstatus.setText(eachdata[9])


    def viewintable(self,data):
        self.hiddingWidgets()
        self.table.show()
        count = data[0]
        for number in count:
            no = int(number[0])
        self.table.setRowCount(no+8)
        for i in range(0,no+8):
            for j in range(0,10):
                self.table.setItem(i,j,QTableWidgetItem(""))
        i =0
        details = data[1]
        for each_detail in details:
            if i <= no:
                self.table.setItem(i,0,QTableWidgetItem(str(each_detail[0])))
                self.table.setItem(i,1,QTableWidgetItem(str(each_detail[1])))
                self.table.setItem(i,2,QTableWidgetItem(str(each_detail[2])))
                self.table.setItem(i,3,QTableWidgetItem(str(each_detail[3])))
                self.table.setItem(i,4,QTableWidgetItem(str(each_detail[4])))
                self.table.setItem(i,5,QTableWidgetItem(str(each_detail[5])))
                self.table.setItem(i,6,QTableWidgetItem(str(each_detail[6])))
                self.table.setItem(i,7,QTableWidgetItem(str(each_detail[7])))
                self.table.setItem(i,8,QTableWidgetItem(str(each_detail[8])))
                self.table.setItem(i,9,QTableWidgetItem(str(each_detail[9])))
            i = i+1


    def hiddingWidgets(self):
        self.table.hide()
        self.rollno.hide()
        self.enterrollno.hide()
        self.widget.hide()
        self.widget1.hide()
        self.widget2.hide()
        self.widget3.hide()
        self.widget4.hide()
        self.layoutWidget.hide()
        self.layoutWidget_2.hide()
        self.layoutWidget_3.hide()


class SearchforDeletePage(QWidget):
    def __init__(self, parent= None):
        super(SearchforDeletePage, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                           "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                           "border-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(60, 100, 641, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 721, 301))
        self.frame_2.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                                   "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                                   "border-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.heading = QtWidgets.QLabel("Delete Student",self)
        self.heading.move(80,90)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.heading.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.searchButton = QtWidgets.QPushButton(self.frame_2)
        self.searchButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                            "background-color: qconicalgradient(cx:0, cy:0,"
                                            " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                            " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                            " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                            " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                            "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                            " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.searchButton.setGeometry(QtCore.QRect(60, 100, 131, 31))
        self.searchButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 50, 271, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rollno = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollno.setFont(font)
        self.rollno.setObjectName("label")
        self.horizontalLayout.addWidget(self.rollno)
        self.enterrollno = QtWidgets.QLineEdit(self.widget)
        self.enterrollno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterrollno.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.enterrollno)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.rollno.setText(_translate("Form", "Roll No:"))
        self.searchButton.setText(_translate("Form", "Search"))

    def searchrollno(self,deletepage):
        rollno = self.enterrollno.text()
        try:
            if int(rollno)>0:
                self.viewdata = ViewStudentData(rollno,'Single')
                data = self.viewdata.returndata()
                deletepage.viewdatatodelete(data)
                return True
        except ValueError:
            return False


class deleteStudentPage(QWidget):
    def __init__(self, parent= None):
        super(deleteStudentPage, self).__init__(parent)
        self.setupUi()

    def setupUi(self):
        self.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                           "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                           "border-color: rgb(0, 0, 0);")
        self.frame = QtWidgets.QFrame(self)
        self.frame.setGeometry(QtCore.QRect(60, 100, 641, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 40, 721, 301))
        self.frame_2.setStyleSheet("background-color: rgb(255, 253, 178);border-color: qlineargradient(spread:pad, "\
                                   "x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"\
                                   "border-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.heading = QtWidgets.QLabel("Delete Student",self)
        self.heading.move(80,90)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.heading.setFont(font)
        self.rollno = QtWidgets.QLabel("Roll No:",self)
        self.rollno.move(80,145)
        self.enterrollno = QtWidgets.QLineEdit(self)
        self.enterrollno.move(145,145)
        self.enterrollno.setStyleSheet("background-color: rgb(255,255,255);")
        self.enterrollno.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.rollno.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 100, 271, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.address = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.address.setFont(font)
        self.address.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.address)
        self.enteraddress = QtWidgets.QLineEdit(self.layoutWidget)
        self.enteraddress.setEnabled(False)
        self.enteraddress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enteraddress.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.enteraddress)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(380, 50, 241, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.phnno = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.phnno.setFont(font)
        self.phnno.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.phnno)
        self.enterphnno = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.enterphnno.setEnabled(False)
        self.enterphnno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterphnno.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.enterphnno)
        self.deleteButton = QtWidgets.QPushButton(self.frame_2)
        self.deleteButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                      "background-color: qconicalgradient(cx:0, cy:0,"
                                      " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                      " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                      " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                      " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                      "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                      " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.deleteButton.setGeometry(QtCore.QRect(200, 250, 131, 31))
        self.deleteButton.setObjectName("pushButton")

        self.backButton = QtWidgets.QPushButton(self.frame_2)
        self.backButton.setStyleSheet("background-color: rgb(255, 255, 127);"
                                            "background-color: qconicalgradient(cx:0, cy:0,"
                                            " angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375"
                                            " rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0,"
                                            " 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255,"
                                            " 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 "
                                            "rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625"
                                            " rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.backButton.setGeometry(QtCore.QRect(350, 250, 131, 31))
        self.backButton.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(10, 50, 271, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.name.setFont(font)
        self.name.setObjectName("label")
        self.horizontalLayout.addWidget(self.name)
        self.entername = QtWidgets.QLineEdit(self.widget)
        self.entername.setEnabled(False)
        self.entername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entername.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.entername)
        self.widget1 = QtWidgets.QWidget(self.frame_2)
        self.widget1.setGeometry(QtCore.QRect(380, 100, 241, 21))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gender = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.gender.setFont(font)
        self.gender.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.gender)
        self.maleButton = QtWidgets.QRadioButton(self.widget1)
        self.maleButton.setObjectName("radioButton")
        self.maleButton.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.maleButton)
        self.femaleButton = QtWidgets.QRadioButton(self.widget1)
        self.femaleButton.setObjectName("radioButton_2")
        self.femaleButton.setEnabled(False)
        self.horizontalLayout_4.addWidget(self.femaleButton)
        self.widget2 = QtWidgets.QWidget(self.frame_2)
        self.widget2.setGeometry(QtCore.QRect(10, 150, 271, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DOA = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.DOA.setFont(font)
        self.DOA.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.DOA)
        self.enterdate = QtWidgets.QLineEdit(self.widget2)
        self.enterdate.setEnabled(False)
        self.enterdate.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.enterdate.setObjectName("dateEdit")
        self.horizontalLayout_5.addWidget(self.enterdate)
        self.widget3 = QtWidgets.QWidget(self.frame_2)
        self.widget3.setGeometry(QtCore.QRect(380, 150, 241, 22))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.course = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.course.setFont(font)
        self.course.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.course)
        self.selectcourse = QtWidgets.QLineEdit(self.widget3)
        self.selectcourse.setEnabled(False)
        self.selectcourse.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout_6.addWidget(self.selectcourse)

        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(380, 200, 241, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.feeremaining = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.feeremaining.setFont(font)
        self.feeremaining.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.feeremaining)
        self.enterfee = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.enterfee.setEnabled(False)
        self.enterfee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterfee.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.enterfee)
        self.widget4 = QtWidgets.QWidget(self.frame_2)
        self.widget4.setGeometry(QtCore.QRect(10, 200, 271, 22))
        self.widget4.setObjectName("widget4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.status = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.status.setFont(font)
        self.status.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.status)
        self.showstatus = QtWidgets.QLineEdit(self.widget4)
        self.showstatus.setEnabled(False)
        self.showstatus.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.showstatus.setObjectName("comboBox_2")
        self.horizontalLayout_8.addWidget(self.showstatus)
        self.certificate = QtWidgets.QCheckBox(self.widget4)
        self.certificate.setObjectName("checkBox")
        self.certificate.setEnabled(False)
        self.horizontalLayout_8.addWidget(self.certificate)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)

        self.retranslateUi()


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.address.setText(_translate("Form", "Address:"))
        self.phnno.setText(_translate("Form", "Phone No:"))
        self.deleteButton.setText(_translate("Form", "Delete"))
        self.backButton.setText(_translate("Form", "Back"))
        self.name.setText(_translate("Form", "Name:"))
        self.gender.setText(_translate("Form", "Gender:"))
        self.maleButton.setText(_translate("Form", "Male"))
        self.femaleButton.setText(_translate("Form", "Female"))
        self.DOA.setText(_translate("Form", "Date of Admission:"))
        self.course.setText(_translate("Form", "Course:"))
        self.status.setText(_translate("Form", "Status:"))
        self.certificate.setText(_translate("Form", "Certificate:"))
        self.feeremaining.setText(_translate("Form", "Fess Remaining:"))
        self.enterphnno.setText("")
        self.entername.setText("")
        self.enteraddress.setText("")
        self.enterdate.setText("")
        self.selectcourse.setText("")
        self.maleButton.setChecked(True)
        self.enterfee.setText("0")
        self.certificate.setChecked(False)


    def viewdatatodelete(self,data):
        for eachdata in data:
            self.enterrollno.setText(str(eachdata[0]))
            self.entername.setText(eachdata[1])
            self.enterphnno.setText(eachdata[2])
            self.enteraddress.setText(eachdata[3])
            if eachdata[4] == 'F':
                self.femaleButton.setChecked(True)
            else:
                self.maleButton.setChecked(True)
            self.enterdate.setText(str(eachdata[5]))
            self.selectcourse.setText(eachdata[6])
            self.enterfee.setText(str(eachdata[7]))
            if eachdata[8] == 'Y':
                self.certificate.setChecked(True)
            self.showstatus.setText(eachdata[9])

    def DeleteStudentData(self):
        delete = StudentDataIntoDb()
        if delete.deleteStudentFromDb(self.enterrollno.text()):
            return True
        else:
            return False



